[server]
port = 30001

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
# maxUploadSize = 10000

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
# maxMessageSize = 10000

fileWatcherType = "none"

runOnSave = true

[theme]

backgroundColor="#FFFFFF" # default(white)
# backgroundColor="#000000" # black color
secondaryBackgroundColor="#F0F2F6"

